name: backend

on:
  push: {}
  workflow_dispatch: {}

jobs:
  api-docs-gha:
    name: api docs test on GHA
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
       with:
          repository: getsentry/sentry
          ref: master
          submodules: true

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        id: setup-node
        with:
          node-version-file: ".volta.json"

      - name: Setup sentry python env
        uses: ./.github/actions/setup-sentry
        id: setup
        with:
          mode: default

      - name: Run API docs tests
        # install ts-node for ts build scripts to execute properly without potentially installing
        # conflicting deps when running scripts locally
        # see: https://github.com/getsentry/sentry/pull/32328/files
        run: |
          yarn add ts-node && make test-api-docs

      - name: Inspect failure
        if: failure()
        run: |
          if command -v devservices; then
            devservices logs
          fi

  
  api-docs-depot:
    name: api docs test on Depot
    runs-on: depot-ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
       with:
          repository: getsentry/sentry
          ref: master
          submodules: true

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        id: setup-node
        with:
          node-version-file: ".volta.json"

      - name: Setup sentry python env
        uses: ./.github/actions/setup-sentry
        id: setup
        with:
          mode: default

      - name: Run API docs tests
        # install ts-node for ts build scripts to execute properly without potentially installing
        # conflicting deps when running scripts locally
        # see: https://github.com/getsentry/sentry/pull/32328/files
        run: |
          yarn add ts-node && make test-api-docs

      - name: Inspect failure
        if: failure()
        run: |
          if command -v devservices; then
            devservices logs
          fi